name: CI/CD for Spring Boot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build JAR
      run: ./gradlew clean build -x test

    - name: Setup SSH key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" > $HOME/key.pem
        chmod 400 $HOME/key.pem

    - name: Deploy to EC2
      run: |
        # Stop the service first
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@ec2-3-92-62-56.compute-1.amazonaws.com '
          sudo systemctl stop manajemen-iklan || true
        '
        
        # Create deployment directory if it doesn't exist
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@ec2-3-92-62-56.compute-1.amazonaws.com '
          mkdir -p /home/ubuntu/deployment
        '
        
        # Copy JAR to EC2
        scp -o StrictHostKeyChecking=no -i $HOME/key.pem build/libs/*.jar ubuntu@ec2-3-92-62-56.compute-1.amazonaws.com:/home/ubuntu/deployment/
        
        # Restart services with proper service name
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@ec2-3-92-62-56.compute-1.amazonaws.com '
          sudo systemctl start manajemen-iklan &&
          sudo systemctl enable manajemen-iklan &&
          sudo systemctl restart nginx &&
          sleep 5 &&
          sudo systemctl status manajemen-iklan
        '